-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 11:06:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CIDADE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `ID_CIDADE` INT NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_CIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CINEMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CINEMA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CINEMA` (
  `ID_CINEMA` INT NOT NULL,
  `ID_CIDADE` INT NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  `QTD_ACENTOS` INT NOT NULL,
  PRIMARY KEY (`ID_CINEMA`),
  CONSTRAINT `fk_CIDADE_ID`
    FOREIGN KEY (`ID_CIDADE`)
    REFERENCES `mydb`.`CIDADE` (`ID_CIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CIDADE_idx` ON `mydb`.`CINEMA` (`ID_CIDADE` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`FILME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FILME` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FILME` (
  `ID_FILME` INT NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_FILME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HORARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HORARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HORARIO` (
  `ID_HORARIO` INT NOT NULL,
  `ID_CINEMA` INT NOT NULL,
  `ID_FILME` INT NOT NULL,
  `DT_INICIO_EXIBICAO` DATETIME NOT NULL,
  `DT_FIM_EXIBICAO` DATETIME NOT NULL,
  `QTD_ACENTO_DISPONIVEL` INT NOT NULL,
  `PRECO` DECIMAL NOT NULL,
  `HORARIO` TIME NOT NULL,
  PRIMARY KEY (`ID_HORARIO`),
  CONSTRAINT `fk_CINEMA_has_FILME_CINEMA1`
    FOREIGN KEY (`ID_CINEMA`)
    REFERENCES `mydb`.`CINEMA` (`ID_CINEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CINEMA_has_FILME_FILME1`
    FOREIGN KEY (`ID_FILME`)
    REFERENCES `mydb`.`FILME` (`ID_FILME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_HORARIO_FILME_idx` ON `mydb`.`HORARIO` (`ID_FILME` ASC) INVISIBLE;

CREATE INDEX `fk_HORARIO_CINEMA_idx` ON `mydb`.`HORARIO` (`ID_CINEMA` ASC) VISIBLE;

CREATE UNIQUE INDEX `HORARIO_UNIQUE` ON `mydb`.`HORARIO` (`HORARIO` ASC, `ID_CINEMA` ASC, `ID_FILME` ASC, `DT_INICIO_EXIBICAO` ASC, `DT_FIM_EXIBICAO` ASC) INVISIBLE;

CREATE INDEX `IDX_DT_INICIO_FIM` ON `mydb`.`HORARIO` (`DT_FIM_EXIBICAO` ASC, `DT_INICIO_EXIBICAO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PARAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PARAM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PARAM` (
  `CHAVE` VARCHAR(45) NOT NULL,
  `VALOR` VARCHAR(150) NOT NULL,
  `OBS` VARCHAR(100) NULL,
  PRIMARY KEY (`CHAVE`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CHAVE_UNIQUE` ON `mydb`.`PARAM` (`CHAVE` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`VENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VENDA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VENDA` (
  `ID_VENDA` INT NOT NULL,
  `ID_HORARIO` INT NOT NULL,
  `QTD_INGRESSO` INT NOT NULL,
  `PRECO_TOTAL` INT NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `DT_VENDA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_VENDA`),
  CONSTRAINT `fk_VENDA_HORARIO1`
    FOREIGN KEY (`ID_HORARIO`)
    REFERENCES `mydb`.`HORARIO` (`ID_HORARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_HORARIO_idx` ON `mydb`.`VENDA` (`ID_HORARIO` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
